#!/bin/bash

echo "Options for making the P2P Video Chat publicly accessible:"
echo "Since we now use external TURN server, we don't need Pinggy anymore."
echo ""
echo "Option 1: Deploy to Cloudflare Pages"
echo "  - Install Wrangler: npm install -g wrangler"
echo "  - Login: wrangler login"
echo "  - Deploy: wrangler pages deploy --project-name=p2p-video-chat ."
echo ""
echo "Option 2: Use ngrok"
echo "  - Install ngrok: https://ngrok.com/download"
echo "  - Run: ngrok http 9000"
echo ""
echo "Option 3: Use Cloudflare Tunnel (Cloudflared)"
echo "  - Install cloudflared: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation/"
echo "  - Run: cloudflared tunnel --url http://localhost:9000"
echo ""
echo "Remember to update the peerConfig in index.html with the public URL if needed."